[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build --workspace=examples/vite-emailbuilder-mui"

[deploy]
startCommand = "npx serve -l $PORT -s examples/vite-emailbuilder-mui/dist/"
